### ISSUE TITLE
Machine_batch converge action erases attributes created by recipes during the converge

### ISSUE THREAD

**Issue by bedunbar** [chef/chef-provisioning#116]
It appears to me that when using the converge action on multiple machines (thus triggering a batch to be created) that chef-metal is deleting attributes at the end of the run when it saves the node. See line 55 of machine_batch "m[:spec].save(prefixed_handler)". It is doing a save of the node after the converge is done, but, as far as I can tell, has no way to know what attributes have been added to the node by the recipes that were part of the run list. Thus, when it does the json diff, it deletes the differences.

To verify my suspicion, I have tried with parallelization turned off (auto_batch_machines  false in knife.rb), doing converges one machine at a time and by doing a setup and then a converge_only action (the converge_only action does not do the save after the converge). When I do it any of these ways, the machines converge properly.

When I run with a converge and allow it to use a batch, my converge runs successfully and then there are lines at the end of the log indicating it is updating the node and deleting attributes created by my cookbooks. For example, it is wreaking havoc with my mariadb installation as it is deleting the dynamically saved root password that is saved as an attribute as soon as the machine has been converged.

**Comment by jkeiser** [comment]
This is confirmed fixed by https://github.com/chef/chef-provisioning/pull/294
