### ISSUE TITLE
Authorized ssh key overwritten with metal_default

### ISSUE THREAD

**Issue by jkeiser** [chef/chef-provisioning#131]
This needs investigating--I'm not sure how to characterize the issue, what it is, or if it is an issue.  From issue #111:

This is a bigger problem because if I use metal to build a machine that uses metal, it overwrites the bootstrap users authorized ssh key with metal_default. This means I can't run any metal recipes on it because it only seems to use the user that was ssh'd into the machine (I can't just switch to that user and run it).

Example:
-BOSS_MASTER creates a MASTER-app server using metal, running as ubuntu user
-MASTER-app's role then creates app servers, also using metal and the ubuntu user
-I can then run metal from BOSS_MASTER because nothing overwrote ubuntu's authorized ssh key
-I cannot run metal from MASTER-app because, as part of the machine resource provisioning, the ubuntu users ssh key is overwritten with metal_default key so I can't ssh in as ubuntu

I figure a solution would be to allow the specifying of the metal_default ssh key, but I don't know how things work behind the scenes

**Comment by tyler-ball** [comment]
Closing this since there hasn't been any movement in a while
