### ISSUE TITLE
Hardware matching

### ISSUE THREAD

**Issue by jkeiser** [chef/chef-provisioning#135]
It would be really useful to be able to say "I want 8G dammit" and get a machine with 8G, regardless of the underlying hardware.  We should figure out if there is a way to do this that is intuitive while still being flexible enough to let people match on obscure new hardware a particular cloud or metal vendor has available.

**Comment by randomcamel** [comment]
We're currently evaluating the API going forward, so let's keep this in mind, but there are no plans to implement it for the time being.
