### ISSUE TITLE
Chef-metal-fog with digital ocean doesn't seem to like large ssh keys

### ISSUE THREAD

**Issue by jdblack** [chef/chef-provisioning#140]
'''
jblack@comet:~/chef/linuxguru$ cat recipes/stack_simple.rb 
require 'chef_metal_fog'

with_driver 'fog:DigitalOcean',
     :digitalocean_api_key => Chef::Config[:digital_ocean_api_key],
     :digitalocean_client_id => Chef::Config[:digital_ocean_client_id]

with_chef_server 'https://chef.linuxguru.net',
   :client_name => Chef::Config[:node_name],
   :signing_key_filename => Chef::Config[:client_key]

with_machine_options(
:bootstrap_options => {
      image_name: 'Ubuntu 14.04 x64',
      flavor_name: '512MB',
      region_name: 'New York 2',
      ssh_key_ids:  [ 174936  ]
   }
)

machine 'testbox' do
   tag 'itsname'
end

jblack@comet:~/chef/linuxguru$ sudo chef-client -o linuxguru::stack_simple
[2014-08-24T01:36:22-07:00] WARN: 

---

SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:

```
  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true
```

To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:

```
  knife ssl check -c /etc/chef/client.rb
```

---

Starting Chef Client, version 11.14.6
[2014-08-24T01:36:23-07:00] WARN: Run List override has been provided.
[2014-08-24T01:36:23-07:00] WARN: Original Run List: [recipe[linuxguru::role_linuxguru]]
[2014-08-24T01:36:23-07:00] WARN: Overridden Run List: [recipe[linuxguru::stack_simple]]
resolving cookbooks for run list: ["linuxguru::stack_simple"]
Synchronizing Cookbooks:
- apache2
- iptables
- logrotate
- pacman
- freebsd
- apt
- asterisk
- build-essential
- unimrcp
- yum
- bind
- linuxguru
- bind9
- chef-client
- cron
- chef-server
- elasticsearch
- ark
- windows
- chef_handler
- 7-zip
- git
- dmg
- runit
- yum-epel
- gitolite
- perl
- hostname
- hostsfile
- iptables-ng
- java
- jenkins
- kibana
- lxc
- dpkg_autostart
- mysql
- yum-mysql-community
- nfs
- line
- openvpn
- rsyslog
- selinux
- ssh-keys
- sudo
- swap
- sysctl
- ohai
- td-agent
- users
- zenoss
- openssh
- openssl
- chef-sugar
- rabbitmq
- erlang
- yum-erlang_solutions
- zenoss_client
- redisio
- ulimit
  Compiling Cookbooks...
  Converging 1 resources
  Recipe: linuxguru::stack_simple
- machine[testbox] action converge[2014-08-24T01:36:31-07:00] WARN: Mismatched key size!  /home/jblack/.ssh/id_rsa is 4096 bytes, desired is 2048 bytes.  Use action :regenerate to force key regeneration.
  # 
  # Error executing action `converge` on resource 'machine[testbox]'
  ## Fog::Errors::Error
  
  fog_key_pair[id_rsa](basic_chef_client::block line 18) had an error: Fog::Errors::Error: {"status"=>"ERROR", "error_message"=>"SSH Key failed to be created", "message"=>"SSH Key failed to be created"}
  ## Resource Declaration:
  # In /var/chef/cache/cookbooks/linuxguru/recipes/stack_simple.rb
  
   23: machine 'testbox' do
   24:    tag 'itsname'
   25: end
   26: 
  ## Compiled Resource:
  # Declared in /var/chef/cache/cookbooks/linuxguru/recipes/stack_simple.rb:23:in `from_file'
  
  machine("testbox") do
    action :converge
    retries 0
    retry_delay 2
    guard_interpreter :default
    chef_server {:chef_server_url=>"https://chef.linuxguru.net", :options=>{:client_name=>"comet", :signing_key_filename=>"/etc/chef/client.pem"}}
    driver "fog:DigitalOcean"
    machine_options {:bootstrap_options=>{:image_name=>"Ubuntu 14.04 x64", :flavor_name=>"512MB", :region_name=>"New York 2", :ssh_key_ids=>174936}}
    cookbook_name "linuxguru"
    recipe_name "stack_simple"
    attribute_modifiers [["tags", #Proc:0x000000051b3af0@/var/lib/gems/1.9.1/gems/cheffish-0.7.1/lib/cheffish.rb:149]]
  end

Running handlers:
[2014-08-24T01:36:31-07:00] ERROR: Running exception handlers
Running handlers complete
[2014-08-24T01:36:31-07:00] ERROR: Exception handlers complete
[2014-08-24T01:36:31-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 9.61786178 seconds
[2014-08-24T01:36:31-07:00] ERROR: machine[testbox](linuxguru::stack_simple line 23) had an error: Fog::Errors::Error: fog_key_pair[id_rsa](basic_chef_client::block line 18) had an error: Fog::Errors::Error: {"status"=>"ERROR", "error_message"=>"SSH Key failed to be created", "message"=>"SSH Key failed to be created"}
[2014-08-24T01:36:31-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
'''

**Comment by jakshi** [comment]
The reason for:

[2014-08-24T01:36:31-07:00] ERROR: machinetestbox had an error: Fog::Errors::Error: fog_key_pairid_rsa had an error: Fog::Errors::Error: {"status"=>"ERROR", "error_message"=>"SSH Key failed to be created", "message"=>"SSH Key failed to be created"}

error is that fog_key_pair create duplicated keys on DO, that forbidden by DO API.
