### ISSUE TITLE
Can I run more than one chef-client at once?

### ISSUE THREAD

**Issue by dvlscm** [chef/chef-provisioning#166]
Simplifying a bit, here's what I'm trying to do, and I don't know if it's a Chef limitation or a Metal limitation keeping me from doing it:
- **I want to create clusters of boxes in parallel.** I used to do this in multiple threads when I was using chef-solo/knife-solo to provision machines. Now I'm trying to run `chef-client` multiple times simultaneously.
- **I want to create machines for each cluster in parallel.** I used to do this when I used the AWS SDK to create instances directly.

I've changed the second item to fit the Metal paradigm of creating the machines with a `machine_batch`, which handles parallelization for me. That's fine. But the first item is a serious burr in the saddle, in two ways:
First, I get errors like this when I try to run `chef-client -z` to create the machines in the batch:

```
[2014-09-11T08:16:51-04:00] FATAL: Errno::EADDRINUSE: Address already in use - bind(2) for [fe80::1%lo0]:8889
```

That's understandable, since the client uses port 8889 by default. Looks like Chef 11.16 doesn't actually fix this problem, even though @jkeiser thought it would dynamically find an open for me. When I pass in a port to use (`--chef-zero-port=X`), I can get around that problem.

Second, I get errors like this even when I use unique ports for each `chef-client` run:

```
[2014-09-11T08:20:26-04:00] WARN: Chef client  is running, will wait for it to finish and then run.
```

That second item is the kicker, I think. [This code](https://github.com/opscode/chef/blob/master/lib/chef/run_lock.rb) suggests that `chef-client` is trying to acquire an exclusive systemwide lock to run. If it can't get it, it blocks until the previous run finishes, which defeats my goal of running multiple clients simultaneously so I can create clusters in parallel. That problem didn't show up when I used chef-solo, of course, because that was running on the target machine, not on the machine orchestrating the process.

Questions:
- Is it true that I can run only one instance of `chef-client` at a time?
- Is there a way in metal to run a "batch of batches," meaning a `machine_batch` within a `machine_batch` I assume?

**Comment by Fodoj** [comment]
Short quiestion regarding this issue. I have a similar (well, exactly the same) use case, but I really need to run multiple chef-clients. As each recipe doesn't really modify provisioner node itself, I am asking of doing something like this:

`chef-client -o "recipe[my_cookbook::roll_out_cluster]" --lockfile /tmp/cluster_${timestamp}.pid`

Then I can run as many clients as I need, right? What do you think about this approach?

**Comment by jessehu** [comment]
The same question is posted on https://github.com/chef/chef/issues/6134. I'm able to use '--lockfile' to run two 'chef-client -z' in parallel, and they won't wait for the other to complete, e.g.

chef-client -z --listen mycluster1.rb  --lockfile /tmp/chef1.pid &
chef-client -z --listen mycluster2.rb  --lockfile /tmp/chef2.pid &

And here is my chef version:
$ chef -v
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
