### ISSUE TITLE
custom bootstrap?

### ISSUE THREAD

**Issue by timspencer** [chef/chef-provisioning#169]
I can't see a way to use a custom bootstrap.  We have a custom bootstrap that installs some databag keys and hooks the server into our CloudPassage grid, etc.  So we do something like this to launch our hosts:

knife <cloudprovider> server create --template-file bootstrap/cloudpassage.erb blah blah blah

Is there a way for us to supply this instead of whatever is being used now?  Thanks, and have fun!

**Comment by shortdudey123** [comment]
@jkeiser they are useful when you want to do extra stuff during a chef bootstrap. Examples include running chef more than once, and custom logic to determine the chef version and download path.  It is easier to not have to copy the logic into the chef-provisioning format and maintain 2 locations.
