### ISSUE TITLE
machine_batch convergence cookbook synchronization very slow

### ISSUE THREAD

**Issue by dvlscm** [chef/chef-provisioning#172]
It's taking easily 5 minutes or more when I'm converging 4 machines in a machine_batch. That might be normal, but it sure lengthens the time to converge machines. Not sure if this is a metal issue or not. I found this issue for Chef itself:

https://tickets.opscode.com/browse/CHEF-4423

That might be the same problem I'm seeing, but the later comments there make it sound like it should've been fixed in 11.16. Then again, I wonder if maybe I'm not actually running Chef 11.16 at all. When I run the client and converge machines (4 in this case), I see this at the start:
```
Starting Chef Client, version 11.16.0
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2014-09-13T11:34:40-04:00] WARN: Node darkcastle.local has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/Users/me/project_root/cluster_bake.rb
  * machine_batch[default] action converge
    - [box1] update node box1 at http://127.0.0.1:8901
    - [box1]   update run_list from [] to ["recipe[pipeline]"]
    - [box2] update node box2 at http://127.0.0.1:8901
    - [box2]   update run_list from [] to ["recipe[pipeline]"]
    - [box3] update node sample-public-web-app at http://127.0.0.1:8901
    - [box3]   update run_list from [] to ["recipe[pipeline]"]
    - [box4] update node sample-public-db at http://127.0.0.1:8901
    - [box4]   update run_list from [] to ["recipe[pipeline]"]
    - [box2] generate private key (2048 bits)
    - [box2] create directory /etc/chef on box2
    - [box2] write file /etc/chef/client.pem on box2
...
```
That certainly looks like I'm running with Chef 11.16.0. But later in the run, I see this:
```
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Starting Chef Client, version 11.14.2
- [box3] write file /etc/chef/ohai/hints/ec2.json on box3
- [box4] write file /etc/chef/client.rb on sample-public-db
- [box3] write file /etc/chef/client.rb on sample-public-web-app
- [box1] waiting for box1 (i-9d843676 on fog:AWS:...:) to be connectable (transport up and running) ...
[box3] [2014-09-13T15:36:15+00:00] WARN:
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
[box2] resolving cookbooks for run list: ["pipeline"]
...
```
That references Chef Client version 11.14.2, so I'm confused about what's actually running. If 11.14.2. is, then maybe that would explain me not getting the benefit of something in 11.16.0. But it sure looks like my system has Chef 11.16.0 installed, along with the most updated metal stuff:
```
± gem list chef

*** LOCAL GEMS ***

chef (11.16.0, 11.16.0.rc.0, 11.14.6, 11.14.2, 11.12.8, 11.10.4, 11.6.2)
chef-metal (0.14.2, 0.14.1)
chef-metal-fog (0.9, 0.8)
chef-zero (2.2, 2.0.2, 1.7.3)
cheffish (0.8.1, 0.7.1)
chefspec (4.0.2, 4.0.1)
```
Questions:
* Is that "conflict" between 11.14.2 and 11.16.0 a known issue already? Alternatively, is it not really a conflict at all?
* Is there something special I need to set in machine_options or elsewhere to keep synchronization from bogging down?
* If not, is there perhaps something funky going on with chef-zero that doesn't take advantage of the synchronization speed increase mentioned in that Chef issue I linked to?

**Comment by tyler-ball** [comment]
I think  we made changes to cookbook syncing in later versions of chef-provisioning that should have helped this issue.  Please file a new issue if you are experiencing this in the latest version of chef-provisioning!
