### ISSUE TITLE
Output doesn't stream when run within non-login session.

### ISSUE THREAD

**Issue by curiositycasualty** [chef/chef-provisioning#176]
All I get is the below when executing `chef-client -z ...` via `bundle exec ...`

```
[2014-09-17T16:49:25-07:00] INFO: Executing sudo chef-client -l info on vagrant@127.0.0.1
[2014-09-17T16:57:47-07:00] INFO: Completed chef-client -l info on vagrant@127.0.0.1: exit status 0
```
despite --stream defaulting to true: https://github.com/opscode/chef-metal/blob/41d180f232b1a4c6f954adbe9695ab2330cd6517/bin/metal#L75

**Comment by tyler-ball** [comment]
@curiositycasualty I haven't seen this issue in recent versions of chef-provisioning, so I'm going to close this.  Please re-open if you still have an issue!
