### ISSUE TITLE
action :delete & action :destroy

### ISSUE THREAD

**Issue by matiasdecarli** [chef/chef-provisioning#186]
Reading the docs, I can see that "delete" is a option for the machine resource

![screen shot 2014-10-02 at 4 23 59 pm](https://cloud.githubusercontent.com/assets/2442390/4496840/bce26598-4a69-11e4-9e02-4808aa179ca1.png)

But when I use it

```
  Chef::Exceptions::ValidationFailed
  ----------------------------------
  Option action must be equal to one of: nothing, allocate, ready, setup, converge, converge_only, destroy, stop!  You passed :delete.
  
  Cookbook Trace:
  ---------------
    /home/vagrant/cookbooks/matiasdecarli/recipes/create_container.rb:55:in `block in from_file'
    /home/vagrant/cookbooks/matiasdecarli/recipes/create_container.rb:52:in `from_file'
  
  Relevant File Content:
  ----------------------
  /home/vagrant/cookbooks/matiasdecarli/recipes/create_container.rb:
  
   50:  
   51:  machine "deploy-to-delete" do
   52>>   action :delete
   53:  end
   54: 
```
Am I doing something wrong here? I can use destroy, but this doesnt delete the node, only the container. Thanks in advance

**Comment by jkeiser** [comment]
This is fixed.  https://docs.chef.io/resource_machine.html#actions

As for autogenerating docs, it's definitely on a list.  Will take some sphinxing though.  @jamescott and I have talked about it, but we haven't got to it yet.
