### ISSUE TITLE
ChefMetal::ConvergenceStrategy::PrecreateChefObjects does not support proxy settings

### ISSUE THREAD

**Issue by justindossey** [chef/chef-provisioning#187]
When a machine to be created needs to use a proxy server for convergence, Chef allows us to write `http_proxy`, `https_proxy`, and `no_proxy` to `client.rb`.  `ChefMetal::ConvergenceStrategy::PrecreateChefObjects#client_rb_content` should also include these variables when specified appropriately.

**Comment by tyler-ball** [comment]
Closing this since the latest version of chef-provisioning supports `convergence_options[:bootstrap_proxy]` which translate to `http_proxy` and `https_proxy` in the client.rb config
