### ISSUE TITLE
Xen server VM provisioner

### ISSUE THREAD

**Issue by HenrikSkriver** [chef/chef-provisioning#2]
Hi
I was very excited when I came across this project hoping it can simply and replace our current xen-provision cookbook which we use to create ubuntu VMs on our Xen servers.
But I am guessing that the Xen provisioner needs to be written first before I am really happy. :)
Any plans on that  - do you know if someone is doing this?
It does not appear to be in your trello project though.
Thank in advance.

**Comment by randomcamel** [comment]
Closing, as this is not currently on the roadmap.

**Comment by Sliim** [comment]
Hi!
why this issue is mentionned in the ChangeLog ? It appears in the "Fixed bugs" section of release v1.3.0. But it was closed without any changes..

Any news about provisioning on a Xen server?
