### ISSUE TITLE
chef-metal is nuking 'normal' attributes on every converge.

### ISSUE THREAD

**Issue by AmandaCameron** [chef/chef-provisioning#209]
According to https://docs.getchef.com/essentials_cookbook_attribute_files.html 'normal' attrbutes are supposed to be persisted in the node object. However, chef-metal (or possibly chef-zero) seems to be nuking them on every converge, causing mayham in the development of a cookbook.

**Comment by causton81** [comment]
I tracked this down to cheffish.  I submitted a rough patch to cheffish, but not sure if issue should be fixed in cheffish or chef-provisioning.

**Comment by causton81** [comment]
I wrote a small demo of this problem:
https://github.com/causton81/issue-demos/tree/chef-provisioning-209

**Comment by jkeiser** [comment]
The PR in question was at https://github.com/chef/cheffish/pull/32 .  Looking at this now.  Thanks tons @causton81!

**Comment by jkeiser** [comment]
Also, I adore your issue repro.  So useful.

**Comment by causton81** [comment]
Glad the repro was useful. chef-provisioning is a really cool project. Thanks for all the great work!
