### ISSUE TITLE
manual hydrate needed with chef_data_bag on create

### ISSUE THREAD

**Issue by lynchc** [chef/chef-provisioning#242]
I found this issue when creating the EIP provider in chef-provisioing-aws. the easiest way to repeat is to use that provider with a sample file like this:

```ruby
require 'chef/provisioning/aws_driver'
with_driver 'aws'

with_data_center 'us-west-2' do

    machine "SVR_OR_JUNK" do
	machine_options :bootstrap_options => {
          :key_name => 'SVR_Prov'
	}
    end

#create a new eip and associate it to the machine
    aws_eip_address "junk_ip_1" do
        machine "SVR_OR_JUNK"
    end

#Try to recreate the same EIP - should do nothing as this is already created
    aws_eip_address "junk_ip_1" do
	action :create
    end

#Disassociate the EIP from the machine but make sure it's still created
   aws_eip_address "junk_ip_1" do
        action :disassociate
    end
end
```

Very important that each time you test this, you much rename the aws_eip_address as this only happens on create.
I you remove the hydrate call I make in the existing_ip method, you'll see that no data is available from the databag after it has been created. I have confirmed that the data is being stored properly and can be retrieved but only if you manually call a hydrate.

**Comment by tyler-ball** [comment]
Closing this because it is so old and hasn't had any movement - please re-open if this is still an issue in the latest chef-provisioning!
