### ISSUE TITLE
visibility for machine_options issue

### ISSUE THREAD

**Issue by MrMMorris** [chef/chef-provisioning#246]
Just creating this so a previously closed ticket that still needs resolving gets visibility 

https://github.com/opscode/chef-provisioning/issues/91

**Comment by jkeiser** [comment]
Right now it's working as designed: `machine_options` is supposed to overwrite all machine options.  It's `add_machine_options` on the machine that will let you merge in new options.  (Do feel free to comment or reopen if this is still an issue.)
