### ISSUE TITLE
Stuck at ssh for centos aws machine

### ISSUE THREAD

**Issue by pradeepbhadani** [chef/chef-provisioning#257]
Hi I am trying to execute simple example of creating machine on AWS .
Somehow, chef-metal creates machine but stuck at SSH. I am able to SSH to a machine from terminal.

can anyone suggest if i am missing something?

mycluster.rb :
require 'chef/provisioning'

with_machine_options :bootstrap_options => { 
  :key_name => 'abc', 
  :image_id => 'ami-0bc9d462', 
  :flavor_id => 'm3.medium',
  :aws_access_key_id => '<key>',
  :aws_secret_access_key => '<secret key>'
}

machine 'my-server4' do
  action :converge
  converge true
end

Complete stacktrace : 
```
[vagrant@aatest examples]$ chef-client -z mycluster.rb 
[2014-12-24T05:59:16+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /home/vagrant/chef-provisioning/docs/examples.
Starting Chef Client, version 11.18.0.rc.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (>= 1.4.0, ~> 1.5)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[2014-12-24T05:59:38+00:00] WARN: Node aatest has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/home/vagrant/chef-provisioning/docs/examples/mycluster.rb
  * machine[my-server4] action converge
    - creating machine my-server4 on fog:AWS:xxxxxx:us-east-1
    -   key_name: "abc"
    -   image_id: "ami-0bc9d462"
    -   flavor_id: "m3.medium"
    -   aws_access_key_id: "<key>"
    -   aws_secret_access_key: "<secret key>"
    - machine my-server4 created as i-3bddadc5 on fog:AWS:xxxxxxxxxxxx:us-east-1
    - Update tags for my-server4 on fog:AWS:xxxxx:us-east-1
    -   Add Name = "my-server4"
    -   Add BootstrapId = "http://localhost:8889/nodes/my-server4"
    -   Add BootstrapHost = "aatest"
    -   Add BootstrapUser = "vagrant"
    - create node my-server4 at http://localhost:8889
    -   add normal.tags = nil
    -   add normal.chef_provisioning = {"location"=>{"driver_url"=>"fog:AWS:xxxxxxxxxxxx:us-east-1", "driver_version"=>"0.11", "server_id"=>"i-3bddadc5", "creator"=>"user/testuser", "allocated_at"=>1419400803, "key_name"=>"abc"}}
    - waiting for my-server4 (i-3bddadc5 on fog:AWS:xxxxxxxxxxxx:us-east-1) to be ready ...
    - my-server4 is now ready
    - waiting for my-server4 (i-3bddadc5 on fog:AWS:xxxxxxxxxxxx:us-east-1) to be connectable (transport up and running) ...[2014-12-24T06:03:17+00:00] WARN: Machine my-server4 (i-3bddadc5 on fog:AWS:xxxxxxxxxxxx:us-east-1) was started but SSH did not come up.  Rebooting machine in an attempt to unstick it ...

    - restart machine my-server4 (i-3bddadc5 on fog:AWS:xxxxxxxxxxxx:us-east-1)
    - update node my-server4 at http://localhost:8889
    -   add normal.chef_provisioning.location.started_at = 1419400999
    - waiting for my-server4 (i-3bddadc5 on fog:AWS:xxxxxxxxxxxx:us-east-1) to be connectable (transport up and running) ...
    ================================================================================
    Error executing action `converge` on resource 'machine[my-server4]'
    ================================================================================
    
    Fog::Errors::TimeoutError
    -------------------------
    The specified wait_for timeout (178.907928639 seconds) was exceeded
    
    Resource Declaration:
    ---------------------
    # In /home/vagrant/chef-provisioning/docs/examples/mycluster.rb
    
     11: machine 'my-server4' do
     12:   action :converge
     13:   converge true
     14: end
     15: 
    
    Compiled Resource:
    ------------------
    # Declared in /home/vagrant/chef-provisioning/docs/examples/mycluster.rb:11:in `from_file'
    
    machine("my-server4") do
      action [:converge]
      retries 0
      retry_delay 2
      guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"aatest", :signing_key_filename=>nil}}
      driver "fog:AWS:xxxxxxxxxxxx:us-east-1"
      machine_options {:bootstrap_options=>{:key_name=>"abc", :image_id=>"ami-0bc9d462", :flavor_id=>"m3.medium", :aws_access_key_id=>"<key>", :aws_secret_access_key=>"<secret key>"}}
      cookbook_name "@recipe_files"
      recipe_name "/home/vagrant/chef-provisioning/docs/examples/mycluster.rb"
      converge true
    end
    

Running handlers:
[2014-12-24T06:06:25+00:00] ERROR: Running exception handlers
Running handlers complete
[2014-12-24T06:06:25+00:00] ERROR: Exception handlers complete
[2014-12-24T06:06:25+00:00] FATAL: Stacktrace dumped to /home/vagrant/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 428.516634644 seconds
[2014-12-24T06:06:25+00:00] ERROR: machine[my-server4] (@recipe_files::/home/vagrant/chef-provisioning/docs/examples/mycluster.rb line 11) had an error: Fog::Errors::TimeoutError: The specified wait_for timeout (178.907928639 seconds) was exceeded
[2014-12-24T06:06:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by pradeepbhadani** [comment]
@johnewart  I tried using ssh_username in machine option , but this lead to ignore my :key_name attribute and set key as "chef_default".

@esciara  I tried using my laptop and aws instance to provision new machine instead of vagrant but it always stuck at SSH. I tried using your example as well but stuck.

**Comment by esciara** [comment]
@pradeepbhadani I had the same problem and it turned out my default security group was only allowing access to all tcp ports from with itself. Check that the source on your Security Group is `0.0.0.0/0`, or whatever ip your laptop is (if it has a fixed ip).

**Comment by pradeepbhadani** [comment]
@esciara  i am using security group other than "default" and that security group allow ssh connection 0.0.0.0/0 
I am able to successfully SSH from my laptop to EC2 instance if I directly use SSH command. But chef is not able to do login :(

**Comment by pradeepbhadani** [comment]
@esciara  It seems to be issue of  username and i am not able to set the different username.
It always take my laptop username and set as : 
   -   Add BootstrapHost = "pradeep-XPS-15-9530"
    -   Add BootstrapUser = "pradeep"

But AMI has only "root" user and i am not able to specify anywhere in recipe or config file.

did you use same username as you have on AMI?

**Comment by esciara** [comment]
@pradeepbhadani if you look at my https://github.com/esciara/chef-provisioning-examples, you will see that I am not setting any `:image_id`, thus by default an ubuntu 14.04 image is used. I am neither setting any `:username` nor any `:ssh_username`, and it works fine. This is the limit of my experience, I'm afraid.

I suggest you troubleshoot step by step by trying with not setting any `:image_id`, see if it works for you and then step it up from there.

**Comment by pradeepbhadani** [comment]
@esciara  Thanks for helping me out.
It seems to be problem with :image_id.

If i dont specify :image_id , it works and if I specify :image_id it do not work.

but its weird that it has limitation of image_id.

**Comment by pradeepbhadani** [comment]
@johnewart  , if i use ssh_username in machine_options the it ignore :image_id and create ubuntu machine.
is there any way to supply both :image_id and :ssh_username at the same time?

**Comment by johnewart** [comment]
What does your recipe look like? The image id goes in the bootstrap options

**Comment by pradeepbhadani** [comment]
@johnewart  earlier i was using these files to start EC2 instance

aws.rb 
--------------------
require 'chef/provisioning'
with_driver 'fog:AWS'
with_machine_options :bootstrap_options => { 
  :key_name => 'cheftest',   
  :flavor_id => 't1.micro',
  :security_group_ids => "sg-aaaaaaa", 
  :image_id => 'ami-b06a98d8'}
}


machine.rb
------------
require 'chef/provisioning'
machine 'myserver' do
machine_options :ssh_username => 'ec2-user',
     tag 'chef-test'
end

In this case , chef ignore option set in file aws.rb

After trying many combinations , below worked 
I only used one file machine.rb
machine.rb
-----------------------
require 'chef/provisioning'
machine 'myserver' do
machine_options :ssh_username => 'ec2-user',
  :bootstrap_options => { 
  :key_name => 'cheftest',
  :flavor_id => 't1.micro',
  :security_group_ids => "sg-aaaaaaa",
  :image_id => 'ami-b06a98d8'}
	tag 'chef-test'
end

**Comment by jkeiser** [comment]
@pradeepbhadani it looks like adding :ssh_username worked then?  I can see how you were having issues--if you put it inside :bootstrap_options it won't work.  Please reopen or open new issues if it's not better, but it looks like you're in better shape now!
