### ISSUE TITLE
Chef::Config.private_key_paths does not include ~/.chef/keys by default

### ISSUE THREAD

**Issue by esciara** [chef/chef-provisioning#258]
The [current README.rb file states](https://github.com/opscode/chef-provisioning/blob/09abe6252c170e316ce645cb7201739df4d69264/README.md):

> `fog_key_pair` creates a new key pair (if the files do not already exist) and uploads it to AWS (it will toss an error if the key pair already exists and does not match). By default, `fog_key_pair` will look for matching key files in .chef/keys, ~/.chef/keys and ~/.ssh.  If it does not find one, it will place the key in `.chef/keys`.  You can override this path in fog_key_pair, but if you do, you will want to modify `private_key_paths` in your configuration to match.

However, when I run a chef provisioning cookbook with a key pair in ~/.chef/keys, I get the following error message:
```
================================================================================
    Error executing action `converge` on resource 'machine[esc-chef-server-provisioned-machine]'
    ================================================================================

    RuntimeError
    ------------
    Server has key name 'chefserver', but the corresponding private key was not found locally.  Check if the key is in Chef::Config.private_key_paths: .chef/keys, /Users/emmanuelsciara/.ssh
```

Is this a bug? Or is the documentation out of date?

Workaround in to place a `private_key_paths [File.expand_path('./.chef/keys', ENV["HOME"])]` or a `private_key_paths "#{ENV["HOME"]}/.chef/keys" ]` in your `knife.rb` or `client.rb` file.

**Comment by jkeiser** [comment]
It looks to me like we need to add ~/.chef/keys to private_key_paths by default!  This would happen in cheffish.

**Comment by tyler-ball** [comment]
This should be fixed in the latest version of Cheffish - please re-open if you are still experiencing issues!
