### ISSUE TITLE
with_data_center method does not work with chef-provisioning

### ISSUE THREAD

**Issue by smford22** [chef/chef-provisioning#265]
According to the example docs on the chef-provisioning-aws repo, I should be able to define the data center that I want to provision machines in using the `with_data_center` method. That does not however work. The only way that I can define another data center to stand up instances is in my `~/.aws/confg` file with the `region` setting.

Here is what the examples show...

```ruby
with_data_center 'eu-west-1' do
  aws_sqs_queue "mariopipes"

  machine 'bowser' do
    machine_options :bootstrap_options => {
            :key_name => 'aws_key'
      }
  end

  load_balancer "webapp-elb" do
    load_balancer_options :availability_zones => ['eu-west-1a'],
                          :listeners => [{
                               :port => 80,
                               :protocol => :http,
                               :instance_port => 80,
                               :instance_protocol => :http,
                           }]
    machines ['bowser']
  end
end
```

`with_data_center` does not work, and is ignored if used in a recipe.

**Comment by lynchc** [comment]
Can you file this under chef-provisioning-aws? This issue is specific to that provider. I have confirmed it works with the fog provider.

**Comment by jkeiser** [comment]
Yep!  https://github.com/chef/chef-provisioning-aws/issues/85
