### ISSUE TITLE
   The specified wait_for timeout (0.01 seconds) was exceeded

### ISSUE THREAD

**Issue by medyagh** [chef/chef-provisioning#269]
I tried to create a machine and I forgot to give them create_time out and it timed out, but later I waited till the machine finished initializing on amazon, and I run the recipe again (this time I added time out of 5000) which is more than enough for an instance which I already know is in running state now, but I got this error: 
```The specified wait_for timeout (0.01 seconds) was exceeded```

there is no way to fix this for me, unless I delete the node object file and re-create the instance.

is there way to just provision the instance that was initialized and avoid re-creating it?

**Comment by jkeiser** [comment]
This is a crappy experience.  We should make it not show this timeout.  In general, @medyagh, the issue is often that Provisioning doesn't have the same keys/username for ssh as the instance itself.

**Comment by tyler-ball** [comment]
We made many updates recently to the waiting experience - this should no longer be an issue.  Please re-open if it is!
