### ISSUE TITLE
There doesn't seem to be a way to define provider specific settings for Vagrant

### ISSUE THREAD

**Issue by vinyar** [chef/chef-provisioning#271]
Example. If I want to expose GUI mode for Windows, in a typical Vagrant file I would do below. I can't seem to figure out a way to define same behavior.

```ruby
...
config.vm.provider :virtualbox do |p|
  p.gui = true
  p.customize ["modifyvm", :id, "--memory", "1500", "--clipboard", "bidirectional", "--natdnshostresolver1", "on"]
end
...
```

**Comment by esciara** [comment]
Here is what I found on the web to do vagrant specific things:
```
with_machine_options :vagrant_config  => <<-ENDCONFIG
config.vm.box = "precise64"
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
  v.cpus = 2
end
ENDCONFIG
```
I don't find it pretty but it's all I managed to find... See https://github.com/esciara/chef-provisioning-examples/blob/1a16ca8b11838b75d9774cafc26645ece5f50012/vagrant_setup.rb for a full example .

**Comment by vinyar** [comment]
woot. I didnt cross my mind to try a heredoc

**Comment by jkeiser** [comment]
Yep :)
