### ISSUE TITLE
Windows hosts are bootstrapped with the wrong url for chef-client

### ISSUE THREAD

**Issue by adamedx** [chef/chef-provisioning#327]
For Windows hosts, it appears we use the url `'https://www.chef.io/chef/install.msi'`. This retrieves the latest version of chef-client for Windows, but the correct source is actually omnitruck. This is what `knife-windows` does, see https://github.com/chef/knife-windows/blob/0.8.4/lib/chef/knife/bootstrap/windows-chef-client-msi.erb#L110. Alternatively, `chef-provisioning` could simply use `knife-windows` to perform the bootstrap since it also handles authentication / SSL configuration.

Without this fix, provisioning depends on a url that may go away and also does not allow for the retrieval of a specific version. Provisioning currently doesn't honor the convention in knife bootstrap that nodes be bootstrapped with the latest minor version of the version of of Chef running knife, for instance.

**Comment by thommay** [comment]
Spiking a solution to this currently
