### ISSUE TITLE
Add support for reserved instances

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning#351]
Acceptance Criteria: As a infrastructure manager I want to create machines which use 'reserved instances' to save my company money.

We should support creating, updating and deleting these instances.  We're not going to worry about selling contracts.

The documentation needs to be clear that this just creates the _reservation_, not the instances.  Instances are created the same way they were previously, using `machine`.  But if they fit the reservation requirements then they get the reduced rate.

- [ ] How expensive is this to test?  Will it cost us $100s of dollars?  Can we get AWS to give us a bunch of credits, even if its in a special account?
- [ ] Is this even that important?  Seems like a long contract when you can't switch from m2 -> m3.

**Comment by fnichol** [comment]
After looking at this feature, it seems like adding support for reserved instances (the act of purchasing a lease) has pretty low value and is most likely a one-time activity. At this point in time, there are no immediate plans to implement this, but we'll reserve the right to change our minds :smile:
