### ISSUE TITLE
Update to the SDK V2

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning#353]
It doesn't depend on Nokogiri!

**Comment by fnichol** [comment]
@tyler-ball was this close a mis-fire?

**Comment by tyler-ball** [comment]
Nope - I meant to file https://github.com/chef/chef-provisioning-aws/issues/216 (in `chef-provisioning-aws` instead of `chef-provisioning`)

**Comment by fnichol** [comment]
Ah, right!
