### ISSUE TITLE
Merge Chef-maintained drivers into the chef-provisioning repo

### ISSUE THREAD

**Issue by randomcamel** [chef/chef-provisioning#354]
This will ease testing and development. Users will still interact with the drivers as separate gems. We'll have some decisions to make around whether and how to migrate issues and PRs, but those need not block moving the code.

**Comment by stuartpreston** [comment]
Is there a definition of which drivers would be impacted by this?  How do you define 'chef-maintained'?

**Comment by randomcamel** [comment]
@stuartpreston Those drivers under the Chef Software org, which I believe are these (I may be missing one or two):

https://github.com/chef/chef-provisioning-aws
https://github.com/chef/chef-provisioning-azure
https://github.com/chef/chef-provisioning-docker
https://github.com/chef/chef-provisioning-fog
https://github.com/chef/chef-provisioning-google
https://github.com/chef/chef-provisioning-hanlon
https://github.com/chef/chef-provisioning-lxc
https://github.com/chef/chef-provisioning-vagrant

Each driver would remain as a distinct gem, probably under a `drivers` directory in the repo or something similar.

**Comment by stuartpreston** [comment]
@randomcamel Interesting. Won't the merge of all these drivers into a single repository cause issues with branching a single driver for issue resolution, tagging and versioning?  

Also what does 'Q2' refer to in terms of milestone?

**Comment by randomcamel** [comment]
@stuartpreston `Q2` is just a label my team at Chef is using to track stuff we're doing this quarter.

If the drivers live in distinct subdirectories and don't interfere each other (which would break a bunch of stuff anyway), it seems like merges should be okay. If we tag something `chef-aws-provisioning-0.11`, that seems pretty straightforward.

Do you have a specific case in mind where this might be intractably problematic? Wrangling this many repos (and the number will probably only grow) has already caused trouble, so it's definitely a case of thinking this solves more problems than it creates, rather than not creating new problems.

**Comment by randomcamel** [comment]
Exploring other options. Will reopen if merging turns out to be the right way to go.
