### ISSUE TITLE
Add a version compatibility check to ChefDK's `chef verify`

### ISSUE THREAD

**Issue by randomcamel** [chef/chef-provisioning#355]
As a first pass, just run through the `chef-provisioning` versions in ChefDK and verify that all of the included drivers have at least one compatible version. Once the foundation is in place, I'll look at expanding the version checks and also look for other things that `verify` can check.

**Comment by randomcamel** [comment]
Blocked on:

1. Releasing -provisioning 0.7 that works with chef-provisioning 1.x.
1. Rolling 0.7 into ChefDK so `chef verify

**Comment by randomcamel** [comment]
Blocked on:

1. Releasing `chef-provisioning-docker` 0.7 which works with `chef-provisioning` 1.x.
1. Updating chef-dk's `chef-provisioning-docker` to 0.7 so `chef verify chef-provisioning` doesn't break the chef-dk build.

**Comment by tyler-ball** [comment]
So chef-provisioning-docker 0.7 has been released, and we determined that we don't actually package it inside the ChefDK.  If we are going to add it to `chef verify` then we probably need to start including it in the ChefDK, but that shouldn't be hard.  What do you think about that plan?

**Comment by randomcamel** [comment]
Yup: since it's not, https://github.com/chef/chef-dk/pull/433 is now decoupled and can ship any time, pending review/fix/merge.

**Comment by randomcamel** [comment]
Waiting on some test infrastructure.

**Comment by randomcamel** [comment]
Passed CI tests, hopefully this can go into 0.7.0.

**Comment by tyler-ball** [comment]
Closing this because https://github.com/chef/chef-dk/pull/433 got merged and will be released in 0.7.0
