### ISSUE TITLE
remove or update test/acceptance project

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning#363]
This was something we had experimented with last year, and the work was left as it is due to priority work.  This is now out of date, and the momentum to improve it as we built it was lost.  The spec work in the aws driver was the direction we are planning on going at the time.  My vote would be get rid of the clutter.

**Comment by patrick-wright** [comment]
@tyler-ball

**Comment by tyler-ball** [comment]
Agreed - we can just delete the whole folder.  We always have git history if we want to look at it.  @patrick-wright wanna open a PR for this?
