### ISSUE TITLE
Conflicting winrm gem causes knife to fail

### ISSUE THREAD

**Issue by nathenharvey** [chef/chef-provisioning#370]
With the latest chef-provisioning gems installed, knife commands fail.

    chef --version
    Chef Development Kit Version: 0.6.2
    chef-client version: 12.3.0
    berks version: 3.2.4
    kitchen version: 1.4.0

    *** LOCAL GEMS ***

    chef (12.3.0, 12.2.1)
    chef-dk (0.6.2)
    chef-provisioning (1.2.0, 1.1.1)
    chef-provisioning-aws (1.2.1, 1.1.1)
    chef-provisioning-azure (0.3.2)
    chef-provisioning-fog (0.13.2)
    chef-provisioning-ssh (0.0.7)
    chef-provisioning-vagrant (0.8.3)
    chef-vault (2.5.0, 2.4.0)
    chef-zero (4.2.2, 4.2.1, 1.5.6)
    cheffish (1.2, 1.1.2)
    chefspec (4.2.0)

    knife node list
    /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate winrm-s-0.2.4, because winrm-1.3.3 conflicts with winrm (~> 1.2.0) (Gem::ConflictError)
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
            from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
            from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/knife-windows-0.8.5/lib/chef/knife/bootstrap_windows_base.rb:22:in `<top (required)>'
            from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load'
            from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `block in load_commands'
            from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `each'
            from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:44:in `load_commands'
            from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:127:in `load_commands'
            from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:208:in `run'
            from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
            from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
            from /opt/chefdk/bin/knife:51:in `load'
            from /opt/chefdk/bin/knife:51:in `<main>'

**Comment by nathenharvey** [comment]
I can get knife working again by uninstalling 1.3.3 of the winrm gem but then, of course, provisioning fails

      sudo chef gem uninstall winrm -v 1.3.3

**Comment by dblessing** [comment]
Seeing the same issue. In our case we got around it by uninstalling `knife-windows` and `winrm-s` since we don't use Windows.

**Comment by tyler-ball** [comment]
Hey @nathenharvey - `chef-provisioning >= 1.2` and `knife-windows < 1.0` are not compatible together.  ChefDK 0.7.0 will resolve this by including the latest version of both dependencies.  Until then, you'll need to `chef gem uninstall chef-provisioning -v 1.2.0` and `chef gem uninstall chef-provisioning-aws -v 1.2.1`
