### ISSUE TITLE
user_data is not working in provisioning ec2 server

### ISSUE THREAD

**Issue by manjukdvg** [chef/chef-provisioning#375]
I trying to pass userdata while provisioning the ec2 server as per the below script. But user_data is not getting set to the machine . 

    my_dbag = data_bag_item('test','test-dbagitem')    
    cluster_array = my_dbag['cluster_name']    
    cluster_array.each {|cluster|    
    machine cluster do    
      add_machine_options bootstrap_options: {    
        subnet: my_dbag['subnet-id'],    
        image_id: my_dbag['ami-id'],    
        security_group_ids: my_dbag['security-group-ids'],    
        key_name: my_dbag['security-keypair'],    
        instance_type: my_dbag['instance-type'],    
        user_data: "testcluster001"    
       }    
      tag cluster    
      ohai_hints 'ec2' => '{}'    
    end    
    }

**Comment by tyler-ball** [comment]
@manjukdvg What happens if you change `add_machine_options` to `machine_options`?

**Comment by manjukdvg** [comment]
machine_options worked . Thanks a lot.

**Comment by tyler-ball** [comment]
@manjukdvg Great!  I'm going to close this since we resolved the issue
