### ISSUE TITLE
chef 12.4.0 and chef-provisioning have a problem when bootstrapping a node

### ISSUE THREAD

**Issue by jfarr-sds** [chef/chef-provisioning#377]
https://christinemdraper.wordpress.com/2015/01/31/deploying-a-multi-node-application-to-aws-using-chef-provisioning/
When following the steps outlined here I consistently got an error:

RuntimeError: private_key[in_memory] (basic_chef_client::block line 79) had an error: RuntimeError: Could not read private key from none: missing pass phrase?

relevant console output
https://gist.github.com/jfarr-sds/379abe0d626379592fb2#file-gistfile1-txt-L100

and stack trace:
https://gist.github.com/jfarr-sds/8f2f9ff6f83b12c7ae1b

Reverting chef to 12.3.0 resolved the issue

**Comment by tyler-ball** [comment]
Yes, this is certainly an error with Chef 12.4.0.  When I made some code updates to fix that error I started running into errors with bootstrapping no longer working.  Trying to figure out what happened today

**Comment by tyler-ball** [comment]
In 12.3.0 https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/precreate_chef_objects.rb#L54 comes back as nil and in 12.4.0 it comes back as an empty string

**Comment by tyler-ball** [comment]
Pulling in the changes from https://github.com/chef/chef/pull/3605 fixed this issue for me!

**Comment by tyler-ball** [comment]
Leaving this open so that when 12.4.1 is released we can make sure and test this again, as well as ensuring the ChefDK gets that version packaged into it

**Comment by tyler-ball** [comment]
I'm going to close this because these changes are in the latest ChefDK RC (> 0.7.0.rc.3) builds - you can obtain it by following the instructions at https://github.com/chef/chef-dk/blob/master/README.md#pre-release-candiates
