### ISSUE TITLE
Cannot bootstrap FreeBSD (bash is not installed)

### ISSUE THREAD

**Issue by razor-x** [chef/chef-provisioning#381]
I am trying to bootstrap a FreeBSD droplet on DigitalOcean. I can get the Ubuntu one working, but the FreeBSD one fails with

```
RuntimeError
------------
Error: command 'bash -c ' bash /tmp/chef-install.sh'' exited with code 1.
```

At first I thought it was not running this with `sudo`, but then I logged in manually to run the command and remembered bash is not installed on the FreeBSD image! `bash: Command not found.`

I can't see any obvious way to tell this to use `tcsh` instead: https://github.com/chef/chef-provisioning/blob/4638bdf99e048452b5b80e06c118ba2a0a0132a3/lib/chef/provisioning/convergence_strategy/install_sh.rb#L36

Just some more context:

```ruby
with_driver 'fog:DigitalOcean'
fog_key_pair 'my_key'

with_machine_options(
  bootstrap_options: {
    image_distribution: 'FreeBSD',
    image_name: '10.1',
    flavor_name: '512MB',
    region_name: 'San Francisco 1',
    key_name: 'my_key' # side note, this seems to do nothing and always uses chef_default
  },
  sudo: true, # tried with and without this
  ssh_username: 'freebsd')
```

Hopefully it is also prefixing everything with sudo correctly (I think it must as I have set `ssh_user: 'freebsd'` and before this command tries to run I do see, e.g.,

```
- write file /tmp/chef-install.sh on test.example.com
```

**Comment by razor-x** [comment]
Confirmed the issue is that FreeBSD is missing bash: after manually running `sudo pkg install bash` I can converge the host.

**Comment by razor-x** [comment]
Here is a workaround for now:

```ruby
machine 'example.com' do
  action :ready
end

machine_execute 'pkg install -y bash' do
  machine 'example.com'
end

machine 'example.com' do
...
end
```

**Comment by thommay** [comment]
I'm spiking a solution to this currently
