### ISSUE TITLE
Can't connect to EC2 instance in VPC with public IP

### ISSUE THREAD

**Issue by dvlscm** [chef/chef-provisioning#385]
I spin up a box which has a public IP and a public DNS. It's in the public subnet of the default VPC. I can SSH into the machine manually from my command line (Mac OS X) using the public DNS, but I can _not_ connect with the public IP. So that's the baseline scenario.

Looks to me like chef-provisioning creates an the EC2 instance I want, then it tries to SSH into the instance using `ubuntu@[public ip address]`, which won't fly.

Is there a way to tell chef-provisioning to use the public DNS instead when it tries to SSH into machines to converge?

**Comment by tyler-ball** [comment]
While the SSH / WinRM logic is stored in chef-provisioning, determine the correct host is driver specific - moving to https://github.com/chef/chef-provisioning-aws/issues/267
