### ISSUE TITLE
What does the error "missing required parameter name" mean

### ISSUE THREAD

**Issue by three18ti** [chef/chef-provisioning#386]
Hello,

I am attempting to use the vSphere driver for chef-provisioning.  When I run chef-client, the first VM spins up and converges the recipe without issue.  As soon as it gets to the second VM the chef run dies with the error:

        ====================================================================
    Error executing action `converge` on resource 'machine[chef-2]'
        ====================================================================

    RuntimeError
    ------------
    missing required parameter name

    Resource Declaration:
    ---------------------
    # In /home/chef/.chef/local-mode-cache/cache/cookbooks/my_cookbook/recipes/provision.rb

     46:   machine "chef-#{num}" do
     47:     recipe 'my_cookbook::default'
     48:     attribute %w[foo bar] = baz
     48:   end
     49: end

My provisioning recipe (outside of my vSphere configuration) is simply:

    num_servers = 3

    1.upto(num_servers) do |num|
      machine "chef-#{num}" do
        recipe 'my_cookbook::default'
        attribute %w[foo bar] = baz
      end
    end

This is confusing because the error has the machine name in it, and there is literally no difference between machine one and machine ten.

Changing the above lines to the following allows the VM to spin up without issue:

    #1.upto(num_cassandra_servers) do |num|
      machine "chef-2" do
        recipe 'my_cookbook::default'
        attribute %[foo bar] = baz
      end
    #end

The same cookbook runs fine in test kitchen minus the provisioning bit.

Any help is greatly appreciated.

Thanks!

EDIT:

To add further to my confusion, if I create each machine individually by editing the machine name, e.g. replace "chef-#{num}" with "chef-1", "chef-2", "chef-3", the modify the recipe to use the loop, running chef again on the already running vms completes without issue.

**Comment by ChefRycar** [comment]
Hi,

I've seen a couple of similar reports, and I believe the issue may be specific to the vsphere driver. I don't presently have access to vmware infra to repro, but could I trouble you to submit this issue on that project (https://github.com/CenturyLinkCloud/chef-provisioning-vsphere) as well?

**Comment by tyler-ball** [comment]
Moving to https://github.com/CenturyLinkCloud/chef-provisioning-vsphere/issues/18

**Comment by mwrock** [comment]
Thanks for moving! I just pushed v0.7.1 that fixes this.
