### ISSUE TITLE
machine resource fails if audit failures occur

### ISSUE THREAD

**Issue by galenemery** [chef/chef-provisioning#387]
```
================================================================================
Error executing action `converge` on resource 'machine_batch[default]'
================================================================================

RuntimeError
------------
Error: command 'chef-client -l info' exited with code 1.
```

This is due to:

```
 Chef Client finished, 20/24 resources updated in 39.348871933 seconds
   2/4 controls succeeded
```

We shouldn't fail on audit failures.

This is using:
chef-provisioning (1.2.0)
chef-provisioning-aws (1.2.1)
Chef Development Kit Version: 0.7.0.rc.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.1

Provisioning to AWS.  Chef-Server 12 (also running in AWS)

**Comment by jkeiser** [comment]
I don't see a huge difference between the converge failing and the audit failing, do you? In both cases, the server wasn't configured according to your wishes, and that seems like a good reason to fail. Unless I'm missing something about what audit mode means--I thought it was a set of tests you could do to verify that your server is in fact set up the way you want it.

**Comment by tyler-ball** [comment]
Closing this and moving the comments to #393
