### ISSUE TITLE
Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type

### ISSUE THREAD

**Issue by roy-miller** [chef/chef-provisioning#388]
The exact error (after waiting a good long time) looks like this:
```
± chef-client -z test_create.rb
Starting Chef Client, version 12.4.1
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2015-07-13T08:14:19-04:00] WARN: Node darkcastle.local has an empty run list.
Converging 1 resources
Recipe: @recipe_files::mypath/test_create.rb
  * machine[test-machine] action ready[2015-07-13T08:14:19-04:00] WARN: Class Chef::Provider::Machine does not declare 'resource_name :machine'.
[2015-07-13T08:14:19-04:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
[2015-07-13T08:17:08-04:00] WARN: Class Chef::Provider::FogKeyPair does not declare 'resource_name :fog_key_pair'.
[2015-07-13T08:17:08-04:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
[2015-07-13T08:17:09-04:00] WARN: Class Chef::Provider::PrivateKey does not declare 'resource_name :private_key'.
[2015-07-13T08:17:09-04:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.

    - create chef_default on fog:AWS:962196760347:us-east-1 from local key at [2015-07-13T08:17:09-04:00] WARN: Using chef_default key, which is not shared between machines!  It is recommended to create an AWS key pair with the fog_key_pair resource, and set :bootstrap_options => { :key_name => <key name> }

    - creating machine test-machine on fog:AWS:962196760347:us-east-1
    -   instance_type: "m3.medium"
    -   image_id: "myimageid"
    -   key_name: "chef_default"
    =============================================================================
    Error executing action `ready` on resource 'machine[test-machine]'
    =============================================================================

    Fog::Compute::AWS::Error
    ------------------------
    InvalidParameterCombination => Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.

    Resource Declaration:
    ---------------------
    # In /mypath/test_create.rb

     72: machine 'test-machine' do
     73:   action :ready
     74:   machine_options :bootstrap_options => {
     75:     :instance_type => 'm3.medium',
     76:     :image_id => 'myimageid'
     77:   }
     78: end

    Compiled Resource:
    ------------------
    # Declared in /mypath/test_create.rb:72:in `from_file'

    machine("test-machine") do
      action [:ready]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://127.0.0.1:8901", :options=>{}}
      driver "fog:AWS"
      machine_options {:bootstrap_options=>{:instance_type=>"m3.medium", :image_id=>"ami-6d3bf006"}}
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/mypath/test_create.rb"
    end


Running handlers:
[2015-07-13T08:17:11-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-13T08:17:11-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 174.171071 seconds
[2015-07-13T08:17:11-04:00] FATAL: Stacktrace dumped to /Users/me/.chef/local-mode-cache/cache/chef-stacktrace.out
[2015-07-13T08:17:11-04:00] ERROR: machine[test-machine] (@recipe_files::/Users/me/Workspaces/pipefitter/test_create.rb line 72) had an error: Fog::Compute::AWS::Error: InvalidParameterCombination => Non-Windows instances with a virtualization type of 'hvm' are currently not supported for this instance type.
[2015-07-13T08:17:11-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
I'm trying to create an instance with this:
```ruby
require 'chef/provisioning'
with_driver 'fog:AWS', :compute_options => { :aws_access_key_id => 'meykey', :aws_secret_access_key => 'mysecretkey' }
with_chef_local_server :chef_repo_path => 'repopath', :cookbook_path => '/repopath/cookbooks'
machine 'test-machine' do
  action :ready
  machine_options :bootstrap_options => {
    :instance_type => 'm3.medium',
    :image_id => 'myimageid'
  }
end
```
Pretty simple case, I think, but it errors out. The error message is confusing, too. AWS says m3.medium supports HVM, and my ami has virtualization type hvm (I created it, but it says "hvm" right on there), so what's the problem?

I'm not trying to put the instance into a VPC, which I figured would complicate things. I'm not creating the machine in a machine_batch either, which I figured could introduce another variable. I'm also not trying to create an instance type which is only valid in a VPC (e.g., t2.x). So it seems to me that I'm not doing anything out of counts in AWS land or chef provisioning country. 

This is probably just my ignorance at work, but if anybody knows what's causing this, I'd love to hear it.

**Comment by roy-miller** [comment]
This could have something to do with the driver I'm trying to use. Note that I was using `fog:AWS`. That was the only AWS driver available months ago when I last looked at this. Apparently that's not the case now.

The difficulty was apparently using this:
```ruby
machine_options :bootstrap_options => {
  :instance_type => 'm3.medium',
  ...
}
```
The `instance_type` bootstrap option doesn't fly with the fog driver. You have to use `:flavor_id` instead. SSH still times out connecting to the new instance, but I don't see the hvm virtualization error anymore.

So, a few follow-up questions if anybody has the gumption to educate me:
1. Is there documentation about each driver, and what the bootstrap options diffs are between them?
2. Which driver should I be using to set up AWS EC2 instances?
3. If there is no "should", what's the recommended driver?

Thanks.

**Comment by christinedraper** [comment]
There's some provider doc here: https://github.com/chef/chef-provisioning/tree/master/docs/providers

I'd suggest https://github.com/chef/chef-provisioning-aws. It's got more function, it's getting the development effort, and it's not limited to what fits into the generic fog interface. Re bootstrap options, chef-provisioning-aws provides you exactly what is in the options hash for the Ruby V1 API for creating instances 

https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/EC2/InstanceCollection.html#create-instance_method

**Comment by tyler-ball** [comment]
I agree with @christinedraper - use chef-provisioning-aws with for AWS.  It doesn't have the best documentation ([ugh](https://github.com/chef/chef-provisioning-aws#machine-options)) but its getting better.  Check out https://github.com/chef/chef-provisioning-aws/pull/265/files - its my changes in a current PR which show the most up-to-date information on `with_machine_options` (which is also the `machine_options` attribute inside the `machine` resource).

https://github.com/chef/chef-provisioning-aws#prerequesites should specify the prerequisites you need to run `chef-provisioning-aws`.

An example of all the non-base resources can be seen in https://github.com/chef/chef-provisioning-aws/blob/master/docs%2Fexamples%2Fref_full.rb

I'm going to close this issue.  If you have issues with the documentation please open issues against the chef-provisioning-aws project.
