### ISSUE TITLE
Lower the version of chef.

### ISSUE THREAD

**Issue by DarshanMurthy** [chef/chef-provisioning#391]
Hey when I lower the version of chef to 11.16.4.. we are facing below attested error:

ERROR: Unable to activate cheffish-1.2, because chef-zero-2.2.1 conflicts with chef-zero (~> 4.2), chef-11.16.4 conflicts with chef (~> 12.1)

Please, help me to resolve this issue.

Thanks,
Darshan

**Comment by charlesjohnson** [comment]
@DarshanMurthy Chef Provisioning is only compatible with Chef 12 and higher. We recommend you use the latest release of chef-dk to work with it, which can be downloaded here:

https://downloads.chef.io/chef-dk/
