### ISSUE TITLE
Error forwarding port: could not forward 8889 or 0 

### ISSUE THREAD

**Issue by DarshanMurthy** [chef/chef-provisioning#392]
Hey All,

We have been working on "chef provisioning" for our Vsphere. 

This is my config file: https://gist.github.com/DarshanMurthy/c4227990c45eacd8c398

Here's log: https://gist.github.com/DarshanMurthy/c0d61b883bf482ba35e6#file-log.

The bug is : "Error forwarding Port". Please, share some ideas or any pointers are appreciated.

Thanks,
Darshan

**Comment by DarshanMurthy** [comment]
@tyler-ball @jkeiser  Please, help us.

**Comment by christinedraper** [comment]
@DarshanMurthy it'll help if you can also gist the stacktrace, taken just after a failed run. The chef client output will tell you where it is... in the run above, looks like it was:

 /Users/dtumkursreeni/.chef/local-mode-cache/cache/chef-stacktrace.out

**Comment by DarshanMurthy** [comment]
@christinedraper Here's is the stacktrace : https://gist.github.com/DarshanMurthy/639fe0f69ae6c2fbc12f#file-stackoutput

**Comment by tyler-ball** [comment]
Hey @DarshanMurthy sorry about the delay.  I'm guessing you're running `chef-client -z` from your workstation to provision this machine?  When you do that it starts a chef-zero server on your workstation.  Then it tries to forward port 8889 from the target machine to the workstation so when chef-client runs on the target machine it can access `http://localhost::8889` successfully.  It will use the forwarded port to access the chef-zero client on the workstation.

For some reason the port forwarding is failing.  Have you used pry debugging before?  The quickest way to troubleshoot this will be to add `require 'pry'; binding.pry` to https://github.com/chef/chef-provisioning/blob/v1.2.0/lib/chef/provisioning/transport/ssh.rb#L329 and inspect the state of the session.  If there is an SSH error, you should be able to see it in there.  Can you try that?

Another solution is to specify a chef_server to use.  I know @christinedraper has done that before.  @christinedraper are the instructions at https://github.com/chef/chef-provisioning#pointing-boxes-at-chef-servers still correct?

**Comment by DarshanMurthy** [comment]
@tyler-ball 

Great,  I will try and get back to you. Before that I have a quick question.
Is lower version chef server is compatible with chef-provision? What version (chef -server) you would suggest us to use?

I tried this work around: 

machine "Test30" do
  chef_server( :chef_server_url => 'http://IP:8889')
  run_list ['workspace_provisioning::default']
end

Error Log: https://gist.github.com/DarshanMurthy/9b97ffffa79a52b90201#file-log
Since, we are using lower version of chef-server.. I guess the error.

**Comment by christinedraper** [comment]
I believe the with_chef_server info is correct, although I've been using it with chef-zero and havent needed the signing info.

**Comment by tyler-ball** [comment]
@DarshanMurthy I think chef-provisioning is only compatible with chef-server version 12 and greater.  What server version are you using?

That error looks like a connectivity issue - if you log into the VSphere machine can you curl your chef server?  Are you sure there isn't some kind of firewall preventing communication?

**Comment by DarshanMurthy** [comment]
@tyler-ball 

We are using Chef-server lower than 12... that is the issue I believe. I will update the higher version Chef Server and let you know the results. 

>> I shall check with curling and see if any obstacles...

**Comment by tyler-ball** [comment]
Hey @DarshanMurthy its been a while since we heard from you - I'm going to close this but please re-open or file a new issue if you want to continue troubleshooting!
