### ISSUE TITLE
[Feature Request] Allow chef-provisioning to force a recipe to run, even if it doesn't think it needs to be run

### ISSUE THREAD

**Issue by bbbco** [chef/chef-provisioning#399]
[Feature Request] Allow chef-provisioning to force a recipe to run, even if it doesn't think it needs to be run. It would be nice if you could define an action in the machine/machine_batch to tell chef-provisioning to run the recipe on the nodes.

**Comment by bbbco** [comment]
... And I just discovered the `action :converge_only` command. What I get for actually reading the code!

**Comment by jkeiser** [comment]
@bbbco there is also `converge true`, which you can put on any `machine` resource to tell it to run the run list no matter what (even if it doesn't think it's changed).
