### ISSUE TITLE
:converge action should not re-install chef-client if the desired version is already installed

### ISSUE THREAD

**Issue by ynojima** [chef/chef-provisioning#428]
When run_list or tags are modified in machine resource with converge_only action, run_list and tags are not updated in nodes/<node>.json.

With converge action, run_list and tags in nodes/<node>.json are updated, but converge action consumes time to install chef-client, it is not convenient.
It would be nice if run_list or tags in nodes/<node>.json file are updated on converge_only action to reflect machine resource.

**Comment by tyler-ball** [comment]
Hey @ynojima the `install.sh` script should not be attempting to download and re-install the same version of Chef if it is already installed.  Are you seeing that behavior?

If you are seeing that, and we fixed that issue, would you be okay with the speed of the `:converge`?

I don't want to change the `:converge_only` action to have it do more than it is doing then.  Then it wouldn't be only converging :)

**Comment by ynojima** [comment]
Thank you for comment.

> I don't want to change the :converge_only action to have it do more than it is doing then. Then it wouldn't be only converging :)
I understand your design decision, and I'm ok if `:converge` action re-installs only when proper chef-client is not installed.

> Are you seeing that behavior?
No, I don't. When I used `:converge` action, it seems it always try to re-install chef-client.
I'm using chef-provisioning-ssh as a driver. Maybe it is the cause.

**Comment by tyler-ball** [comment]
I'm going to update this bug to be about investigating how we can not re-install the same version of chef multiple times - perhaps we can leverage `Mixlib::Install` for this?

**Comment by hh** [comment]
I think our functions of interest are [Check-UpdateChef in support/install_command.ps1](https://github.com/chef/mixlib-install/blob/master/support/install_command.ps1#L1) and [should_update_chef in support/install_command.sh](https://github.com/chef/mixlib-install/blob/master/support/install_command.sh#L165) from https://github.com/chef/mixlib-install/blob/master/support/

Some tests around these should make it where we don't re-install.

**Comment by ynojima** [comment]
Thank you for pointing out.
I looked into the install_command.sh script, and I found 'latest' was specified in `$version` since I haven't specified `chef_version` option in `convergence_options`, and 'latest' made chef-client re-installed everytime.
Once I specified `chef_version`, `:converge` action stop re-install chef-client.

For my case, specifying desired chef version in `convergence_options` is solution,
but some may want `latest` not to re-install chef-client if 'latest' chef-client is already installed.

**Comment by hh** [comment]
Nice catch @ynojima  I'll be adding chef_version myself now.

**Comment by hh** [comment]
I can verify that it did not re-install it on windows, However think there is an error in the powershell code:

```
    [awsusw2-ii-mip-demo] Method invocation failed because [Selected.System.String] doesn't contain a 
                                          method named 'StartsWith'.
                                          At C:\chef\install.ps1:19 char:7
    [awsusw2-ii-mip-demo] -----> Chef Omnibus installation detected (12.4.1)
                                          
    [awsusw2-ii-mip-demo] +   if ($chef_version.StartsWith($version)) { return $false }
                                          +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              + CategoryInfo          : InvalidOperation: (StartsWith:String) [], Runtim 
                                             eException
                                              + FullyQualifiedErrorId : MethodNotFound
```

**Comment by martinheg** [comment]
I’m seeing the same behaviour on Windows, where the chef client is downloaded and re-installed each time, when `chef_version` is not specified.
And similarly, when `chef_version` is specified, I see the same powershell error as @hh.

Interestingly (for me at least), I do not see either of these two behaviours when I use `chef provision --no-policy` to do the provisioning  (as opposed to using  `chef-client -z my_provisioning_recipe`).

**Comment by thommay** [comment]
cc @jaym since i stole the powershell from him

**Comment by tyler-ball** [comment]
Okay, here is my story for this:

I'm pinning to Mixlib::Install 0.7.0 until 1.0 is released.  0.7.0 has an install script that won't re-install chef every time _if_ you specify a desired version.  If you don't or you specify `"latest"` then it will re-install every time even if the latest version is already installed.  I talked to @sersut and that behavior will change in Mixlib::Install 1.0.  We will pull in that change when it is released.

In the mean time, specify a version like below to keep chef from re-installing every time:

```ruby
machine "tyler_test_machine" do
  machine_options bootstrap_options: {
    key_name: 'tyler_provisioning_test',
    # ...
  }, convergence_options: {
    chef_version: "12.5.1",
    # ...
  }
end
```
