### ISSUE TITLE
throw exception if Chef::Provisioning::Transport.:WinRM#execute command is over 3040 chars

### ISSUE THREAD

**Issue by hh** [chef/chef-provisioning#432]
I've validated that 3040 is too long https://github.com/WinRb/WinRM/issues/41 so we should look at throwing an error if we are asked to do something we can't do.

**Comment by tyler-ball** [comment]
Hey @hh it looks like this has overlap with https://github.com/chef/chef-provisioning/issues/431.  Can we close this in favor of your suggestion for #431 where we send the file over and execute it with a scheduled task?

**Comment by tyler-ball** [comment]
Closing this in favor of #431
