### ISSUE TITLE
machine attribute in both machine_execute and machine_file resources should be required.

### ISSUE THREAD

**Issue by poliva83** [chef/chef-provisioning#449]
I declared a machine_execute block accidentally without specifying machine attribute. I made a bad assumption that the attribute was `:name_attribute`.

Anyway it failed when trying to connect to the machine but exception thrown was not in spot I expected.

 NoMethodError
    -------------
    undefined method `split' for nil:NilClass

https://github.com/chef/chef-provisioning/blob/63e88632122375476eb40a8a7a2db1e8b6d6b876/lib/chef/provisioning.rb#L46

Since my resources name attribute for resource is nil this [call](https://github.com/chef/chef-provisioning/blob/4638bdf99e048452b5b80e06c118ba2a0a0132a3/lib/chef/provisioning/chef_run_data.rb#L91) ended up setting machine_spec to object containing list of all machine managed entries. Since machine_spec in this case did not contain driver_url you hit the exception.

Suffice to say this confused me enough to have to walk-through the code. With the current implementation of machine_execute and machine_file resources I don't see how they can work without machine attribute declared. If we made the attribute required I believe it would result in error message which shows root cause of problem.

**Comment by tyler-ball** [comment]
Closed by merging https://github.com/chef/chef-provisioning/pull/542
