### ISSUE TITLE
Flexible install_command. Do not assume internet acces. 

### ISSUE THREAD

**Issue by afiune** [chef/chef-provisioning#474]
Currently chef-provisioning assume we have internet access to install chef. It would be super awesome if we could customize the `install_command` coming from here https://github.com/chef/chef-provisioning/blob/master/lib/chef/provisioning/convergence_strategy/install_sh.rb#L44

**Comment by http-418** [comment]
Additionally, README.md includes a convergence option to work around this, `install_sh_url`, but it doesn't actually work.   The `install_sh` convergence strategy uses `mixlib/install`, which ignores the option entirely.

**Comment by http-418** [comment]
It looks like `install_sh_url` last worked in v1.2.1.  Versions v1.3.0 and above moved to mixlib/install.

**Comment by kplimack** [comment]
I'm also hitting this.

**Comment by vmorris** [comment]
Ran into this today.
