### ISSUE TITLE
Can't provision with chef-zero (chef-client -z) and have the node point to a chef-server

### ISSUE THREAD

**Issue by cwandrews** [chef/chef-provisioning#476]
In the docs, it says that one can add the following to their `knife.rb` and have the nodes they provision with `chef-client -z` get pointed to the chef server given:
```ruby
with_chef_server "https://chef.example.com/organizations/yourorg",
  :client_name => Chef::Config[:node_name],
  :signing_key_filename => Chef::Config[:client_key]
```
when I do this the node being provisioned does not attempt to authenticate with my chef-server.

**Comment by fletchowns** [comment]
I ran into this as well. Am I supposed to run my provisioning script a different way if it's pointed at a chef-server?

**Comment by cwandrews** [comment]
@fletchowns I ended up asking on the [mailing list](https://discourse.chef.io/t/cant-provision-with-chef-zero-chef-client-z-and-have-the-node-point-to-a-chef-server/7459) and getting it working. I will send a PR for the documentation change.
