### ISSUE TITLE
machine_batch doesn't clearly mention which machine failed

### ISSUE THREAD

**Issue by ckaushik** [chef/chef-provisioning#499]
When a converge fails in one of the machines in machine_batch, an exception is raised, which is then logged by chef as a failure in machine_batch resource.

This makes exception handling and debugging very hard, especially considering the log lines from different machines are all show in the output at the same time.

If machine_batch can wrap exceptions and add more details, any chef handler on :resource_failed event can then use this exception to identify the machine

**Comment by bbbco** [comment]
:+1:

**Comment by tyler-ball** [comment]
Fixed by merging https://github.com/chef/chef-provisioning/pull/500
