### ISSUE TITLE
Unable to connect to windows instance

### ISSUE THREAD

**Issue by stevehedrick** [chef/chef-provisioning#508]
I have a 
```
machine 'storage' do
  action :converge
end

```

resource.  I'm using the chef-provisioning-vra driver, and the machine is being created (I can rdp to it).  The machine is using the same template as my test-kitchen boxes, which I have no trouble connecting to, but chef-provisioning times out waiting for the machine to become reachable.

snippet of the debug logs:
```
$chef-client -z -o 'cookbook::recipe'
<cut tons of debug stuff>
    - Powering on storage if needed
    - Power on machine storage
    - Waiting for storage to be reachable WARN  WinRM::WinRMWebService : WinRM::WinRMWebService#run_powershell_script is deprecated. Use WinRM::CommandExecutor#run_powershell_script instead
[2016-03-04T15:37:44-05:00] DEBUG: unavailable: network connection failed or broke: #<Timeout::Error: execution expired>

    - been waiting 10/1800 seconds -- sleeping 5 seconds WARN  WinRM::WinRMWebService : WinRM::WinRMWebService#run_powershell_script is deprecated. Use WinRM::CommandExecutor#run_powershell_script instead
[2016-03-04T15:37:59-05:00] DEBUG: unavailable: network connection failed or broke: #<Timeout::Error: execution expired>
```

That message will just repeat for 30 minutes until it times out.  The machine is definitely up.
Is this being caused by not using the commandExecutor or is this something entirely different? 

Version info: 
```
$ chef --version
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
```
```
$ chef gem list chef-provisioning

*** LOCAL GEMS ***

chef-provisioning (1.6.0)
chef-provisioning-aws (1.8.0)
chef-provisioning-azure (0.5.0)
chef-provisioning-fog (0.16.0)
chef-provisioning-vagrant (0.11.0)
chef-provisioning-vra (0.3.0)
```

Grabbing the resource_id and the hostname out of the chef-zero node json file, and inserting them into a `.kitchen/machine.yml` file, then attempting `kitchen converge machine` works with no issues connecting.

Let me know if more info is needed, please.  Not sure if it matters, but I am running this from OSX.

**Comment by stevehedrick** [comment]
So this is interesting.  I'm having the same issue attempting to use chef-provisioing-ssh to winrm into a given machine as well.

Starting to wonder if this isn't due to the winrm version included in chefdk 0.11.2 being 1.7.0.  Will start mucking with the environment tomorrow and try version 1.3.4 that was included in chefdk 0.10.0.

**Comment by stevehedrick** [comment]
Unrelated to version, it's starting to look like the culprit is the corporate overlords fancy cisco vpn software is stomping all over my routing table...

**Comment by chazzly** [comment]
@stevehedrick  - I'm running into precisely the same thing.  Did you figure out what needed to change?  How did you come to this conclusion?

Thanks.
