### ISSUE TITLE
Warn users that they shouldn't use chef-provisioning

### ISSUE THREAD

**Issue by coderanger** [chef/chef-provisioning#549]
It's been long enough, this is now just embarrassing for the community. I wrote up the words, someone just needs to make it clear that use of this repo for new projects/users should be avoided. I'm aware this is an emotional issue for many and we all don't want the dream to die, but the current state of the readme/docs is straight up irresponsible.

**Comment by donwlewis** [comment]
Can a lot of recommended alternatives be generated as well?

**Comment by coderanger** [comment]
@donwlewis The main alternative is Terraform, though SparkleFormation is a solid choice if you fit its more limited scope (i.e. single cloud, slightly fewer services, etc).

**Comment by donwlewis** [comment]
Thanks!  I have been trying to get my hands on terraform for a while just
haven't had the cycles.  My biggest challenge has been finding something
that can work with chef vault during bootstrap.  A lot of my build
cookbooks are pulling secrets from vault.  It's either that or change my
process :)

**Comment by coderanger** [comment]
I'm afraid you're going to probably need to go with the latter, asymmetric pre-encryption systems are not super good at working with automated provisioning in general.

**Comment by donwlewis** [comment]
Yup.  That is what I was afraid of.  Secrets are hard...

**Comment by ajeba99** [comment]
I work with multiple clouds and there isn't that can do what Chef Provisioning does for Windows.  Terraform currently has a show-stopping bug for installing the Chef Client on a Windows server seamlessly.  I use multiple clouds for Sparkle doesn't work and Razor is Puppet.

**Comment by nathenharvey** [comment]
Chef Provisioning is an open source project that falls under the [Chef Maintenance Policy](https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md), has an [identified lieutenant and list of maintainers](https://github.com/chef/chef/blob/master/MAINTAINERS.md#chef-provisioning), and works quite well for a portion of the community.

There is also pretty active discussion in the [#chef-provisioning channel](https://chefcommunity.slack.com/archives/chef-provisioning) in the Chef Community Slack (signup at http://community-slack.chef.io/).

I don't think telling people not to use chef-provisioning is either responsible or the right path forward.

The better path forward is to continue to push for additional maintainers, seek out successes using the tool, and encourage folks to help keep the documentation up-to-date.

I suggest we move forward in two ways:

1.  Discuss this further at next week's Community Summit.
2.  Close this issue.

**Comment by coderanger** [comment]
I don't think discussing this at the summit is a good use of time there. Unless something has changed since my blog post outlining the problems with chef-provisioning ...

**Comment by thehar** [comment]
There are many active users, colleagues and companies using Chef Provisioning. As a maintainer and a user, I think this should be closed.

**Comment by ChadScott** [comment]
@coderanger so, wait... instead of proposing a path to fix what your objections are (haven't read the blog post, sorry) you're proposing just kill the project off?

Terraform is a fine alternative but there's a lot of people invested in chef-provisioning, some deeply. I'd much rather see the community hug this project hard to fill in the missing pieces than just declare it useless.

**Comment by coderanger** [comment]
I'm unsubscribing from this ticket, if people feel it should be closed, go for it.

**Comment by tyler-ball** [comment]
Closing this because I opened https://github.com/chef/chef-provisioning/pull/557. Please take a look at the README updates and let me know if is more straightforward now
