### ISSUE TITLE
Does chef provisioning loadbalancer driver support elbv2

### ISSUE THREAD

**Issue by kamalika-majumder** [chef/chef-provisioning#565]
Hi ,

I am trying to create an application loadbalancer with load_balancer resource but it does not recognise the latest loadbalancer options as per aws doc. I get an error as below:
    
    ArgumentError
    -------------
    unexpected option type

    Resource Declaration:
    ---------------------
    # In /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/dsl/chef_provisioning.rb

     43:             self.#{method_name}(*args, &block)
     44:           end

    Compiled Resource:
    ------------------
    # Declared in /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/dsl/chef_provisioning.rb:43:in `load_balancer'

    load_balancer("pub-elb") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"chefzero://localhost:8889", :options=>{:client_name=>"ip-x-y-x-o", :signing_key_filename=>nil, :api_version=>"0"}}
      driver "aws"
      load_balancer_options {:subnets=>["xxxxxx", "xxxxxx"], :security_groups=>["pub_elb_sg"], :scheme=>"internet-facing", :type=>"application", :attributes=>[{:key=>"idle_timeout.timeout_seconds", :value=>"60"}, {:key=>"deletion_protection.enabled", :value=>"false"}]}
      declared_type :load_balancer
      cookbook_name "infra"
      recipe_name "create_public_elbv2"
    end

    Platform:
    ---------
    x86_64-linux
========================================================

Is there a support for the application load balancer in the driver

**Comment by eheydrick** [comment]
There is no support for ALBs yet. I opened https://github.com/chef/chef-provisioning-aws/issues/502 for adding the feature.
