### ISSUE TITLE
Initial chef-client run on workstation talking to hosted chef-server fails on creating client

### ISSUE THREAD

**Issue by rberger** [chef/chef-provisioning#59]
I'm using the 0.11.beta2 version of chef-metal. 

When I run the initial chef-client run on my workstation to create the machine, it seems to fail when it trys to create the client object on the hosted web server.

I'm guessing that my workstation chef-client doesn't have the permissions to create a new client?

Here's a gist with the last part of the chef-client run output:
https://gist.github.com/rberger/d4a37130dfd2f2869eec

Here's a gist with the stacktrace:
https://gist.github.com/rberger/745bc65fc803b6d91402

**Comment by raskchanky** [comment]
@rberger I re-created the problem you experienced and solved it by using a `client.rb` that looks like this:  https://gist.github.com/raskchanky/0896a31423d2676c7ba5

**Comment by jkeiser** [comment]
So there was a fix a while back for this problem; but it appears to be hosed (at least I'm getting a 400 when it tries to set node permissions for `https://api.opscode.com/organizations/chef-provisioning/nodes/mario/_acl/read`).
