### ISSUE TITLE
Error: Unsupported reporting protocol version - While querying chef reporting api 

### ISSUE THREAD

**Issue by arvind008** [chef/chef-provisioning#621]
## Description
I am trying to fetch the chef logs for chef-client runs, i am getting the logs using knife command line. But i am not able to fetch through Rest API. I am trying to fetch from chef workstation.

I have used CURL based chef authentication specified in https://docs.chef.io/auth.html.
I am able to make chef server API calls, but it fails for chef reporting.

I am getting the following error

{"error":["Unsupported reporting protocol version"]}

## Gem Version
knife-reporting-0.5.0

## Platform Version
Ubuntu 16.04
chef-client 14.10.9

## Replication Case
Use the CURL authentication code and add "X-Ops-Reporting-Protocol-Version=0.1.0".
It gives the expected output for /reports/status 

> {
>   "rest_api" : "online",
>   "sql_db" : "online",
>   "index" : "online"
> }

It fails for all the Chef Reporting API 

Any help on this?

**Comment by jjlimepoint** [comment]
This repository is for the chef provisioning framework very specifically, rather than general issues with provisioning chef.  You might have better luck over at https://github.com/chef-boneyard/knife-reporting , although that is a dead project so probably no-one is watching that one either :(
