### ISSUE TITLE
Allow use of net-ssh 5.2.0 gem

### ISSUE THREAD

**Issue by roperry** [chef/chef-provisioning#622]
## Description
host-key error when using net-ssh-4.2.0

Update the gem specification to use net-ssh-5.2.0.  net-ssh-5.2.0 fixes the following bug:

https://github.com/net-ssh/net-ssh/pull/601

Which occurs when running test kitchen:

 [2019-04-16T11:18:22.977009 #85258] ERROR -- default-Centos7: Message: SSH command failed (host key algorithm mismatch for signature 'ssh-rsa' != 'ssh-rsa-cert-v01@openssh.com')

The latest chef-provisioner and chef gems require net-ssh-4.2.0.

## Gem Version
2.7.6

## Platform Version

Mac OSX. 10.14.4

## Replication Case

Using a bastion host and remote host with the following kex and host_key:

* kex: diffie-hellman-group1-sha1
* host_key: ssh-rsa-cert-v01@openssh.com

Attempt to run `kitchen converge`.

This can be fixed by updating the `chef-provisioning.gemspec` and global specification 
`chef-provisioning-2.7.6.gemspec` files to allow the most recent version.

**Comment by jjlimepoint** [comment]
See PR #623
