### ISSUE TITLE
metal command seems to not use .chef/knife.rb. 

### ISSUE THREAD

**Issue by rberger** [chef/chef-provisioning#70]
The `metal` cli command doesn't seem to use the configuration info in `.chef/knife.rb`. Seems to always use `chef-zero` even if I pass in the chef server url with  -S. And it doesn't seem to pick up any other parameters from `.chef/knife.rb`

**Comment by randomcamel** [comment]
@rberger  There have been quite a lot of changes in all the relevant repos since this was filed: is it still an issue?

**Comment by rberger** [comment]
Heh, not sure. I've been explicitly specifying .chef/knife.rb on the chef-provisioning command line. If John thinks its fixed, its probably fixed.

**Comment by tyler-ball** [comment]
I'm going to close this since we don't support the `metal` CLI anymore, and running `chef-client` has been picking up my local `.chef/knife.rb` file recently
